default:
  gen_usage_db_loc: default
  gen_usage_db_path: !expr system.file("extdata/generation_and_usage.sqlite3", package = "radiantNetDashboard")

local:
  gen_usage_db_loc: user

docker-compose:
  inherits: local